-- generated by @use-transaction/compiler
-- hash: da209a33
-- source: /Users/chasegranberry/Dev/supabase/use-transaction/apps/demo/src/TodoItem.tsx:12
-- update parameter types from 'text' to match your schema
CREATE OR REPLACE FUNCTION ut_da209a33(
  "todoId" text
)
RETURNS SETOF json
LANGUAGE sql
SECURITY INVOKER
AS $$
  UPDATE todos SET completed = NOT completed WHERE id = todoId
$$;
