-- generated by @use-transaction/compiler
-- hash: 60791ffb
-- source: /Users/chasegranberry/Dev/supabase/use-transaction/apps/demo/src/App.tsx:11
-- update parameter types from 'text' to match your schema
CREATE OR REPLACE FUNCTION ut_60791ffb()
RETURNS SETOF json
LANGUAGE sql
SECURITY INVOKER
STABLE
AS $$
  SELECT id, title, completed FROM todos ORDER BY id DESC
$$;
