-- generated by @use-transaction/compiler
-- hash: 48a57c9d
-- source: /Users/chasegranberry/Dev/supabase/use-transaction/apps/demo/src/App.tsx:20
-- update parameter types from 'text' to match your schema
CREATE OR REPLACE FUNCTION ut_48a57c9d(
  "title" text
)
RETURNS SETOF json
LANGUAGE sql
SECURITY INVOKER
AS $$
  INSERT INTO todos (title, completed) VALUES (title, false) RETURNING id, title, completed
$$;
