import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { MigrationAdapter, SqlFunction } from './types.js'

export interface DefaultAdapterOptions {
  outputDir: string
}

export class DefaultAdapter implements MigrationAdapter {
  constructor(private options: DefaultAdapterOptions) {}

  async emit(fn: SqlFunction): Promise<void> {
    await mkdir(this.options.outputDir, { recursive: true })

    if (await this.hasBeenEmitted(fn.hash)) return

    const timestamp = new Date().toISOString().replace(/\D/g, '').slice(0, 14)
    const filename = `${timestamp}_${fn.name}.sql`
    await writeFile(join(this.options.outputDir, filename), buildSQL(fn), 'utf8')
  }

  private async hasBeenEmitted(hash: string): Promise<boolean> {
    try {
      const files = await readdir(this.options.outputDir)
      for (const file of files) {
        if (!file.endsWith('.sql')) continue
        const content = await readFile(join(this.options.outputDir, file), 'utf8')
        if (content.includes(`-- hash: ${hash}`)) return true
      }
    } catch {
      // outputDir does not exist yet — nothing emitted
    }
    return false
  }
}

function buildSQL(fn: SqlFunction): string {
  const paramLines = fn.params.map((p) => `  "${p.name}" text`).join(',\n')
  const paramList = fn.params.length > 0 ? `\n${paramLines}\n` : ''
  const security = fn.security === 'definer' ? 'SECURITY DEFINER' : 'SECURITY INVOKER'
  // STABLE is safe for pure queries; mutations should be VOLATILE (Postgres default).
  const stability = fn.type === 'query' ? '\nSTABLE' : ''

  return `\
-- generated by @use-transaction/compiler
-- hash: ${fn.hash}
-- update parameter types from 'text' to match your schema
CREATE OR REPLACE FUNCTION ${fn.name}(${paramList})
RETURNS SETOF json
LANGUAGE sql
${security}${stability}
AS $$
  ${fn.sql.trim()}
$$;
`
}
